import BooleanAntichainsKernel.IntervalTheorem

#print axioms BooleanAntichainsKernel.intervalAntichainEquivBasis
#print axioms BooleanAntichainsKernel.interval_parallelClassElements
#print axioms BooleanAntichainsKernel.interval_weighted_basis_polynomial
