import BooleanAntichainsKernel.InternalSumAtoms

#print axioms BooleanAntichainsKernel.bottomEmbeddingAtoms_iSupIndep
#print axioms BooleanAntichainsKernel.bottomEmbeddingToInternal
#print axioms BooleanAntichainsKernel.bottomEmbeddingEquivInternal
