import BooleanAntichainsKernel.PartitionContractionFlats

#print axioms BooleanAntichainsKernel.partitionCoarseningContractOrderIso_val
#print axioms BooleanAntichainsKernel.partitionContractionFlatOrderIso
#print axioms BooleanAntichainsKernel.partitionContractionFlatOrderIso_rank
#print axioms BooleanAntichainsKernel.partitionBlockEdgeMap_surjective
#print axioms BooleanAntichainsKernel.partitionContractionFlatOrderIso_mem
#print axioms BooleanAntichainsKernel.partitionContractionFlatOrderIso_preimage
#print axioms BooleanAntichainsKernel.partitionBlockEdgeMap_mem_ground
