import BooleanAntichainsKernel.PartitionContractionBases

#print axioms BooleanAntichainsKernel.partitionSimplification_isBase
#print axioms BooleanAntichainsKernel.partitionSimplificationBasesEquiv
#print axioms BooleanAntichainsKernel.partitionSimplificationBasesEquiv_val
#print axioms BooleanAntichainsKernel.partitionSimplificationBases_count
#print axioms BooleanAntichainsKernel.partitionContractionBasesEquivTrees
#print axioms BooleanAntichainsKernel.partitionContractionBasesEquivTrees_val
#print axioms BooleanAntichainsKernel.partitionRankTight_count_complete_bases
#print axioms BooleanAntichainsKernel.partitionRankTight_count_complete_trees
