import BooleanAntichainsKernel.ProjectiveInternal

#print axioms BooleanAntichainsKernel.internal_summand_finrank_one
#print axioms BooleanAntichainsKernel.orderedProjectiveEquivInternal
#print axioms BooleanAntichainsKernel.orderedProjectiveEquivInternal_apply
#print axioms BooleanAntichainsKernel.maximalSubspaceAntichain_bottom
#print axioms BooleanAntichainsKernel.maximalSubspaceAntichainEquivInternal
#print axioms BooleanAntichainsKernel.maximalSubspaceAntichainEquivInternal_atoms
#print axioms BooleanAntichainsKernel.maximalSubspaceAntichainEquivInternal_coatoms
