import BooleanAntichainsKernel.SizedBlockCoefficients

#print axioms BooleanAntichainsKernel.enumeratedSizedBlocksEquivEmbedding
#print axioms BooleanAntichainsKernel.sizedDisjointBlocks_mul_factorials
#print axioms BooleanAntichainsKernel.sizedDisjointBlocks_count
