import BooleanAntichainsKernel.SizedDisjointBlocks

#print axioms BooleanAntichainsKernel.enumeratedBlocksToEmbedding_injective
#print axioms BooleanAntichainsKernel.sizedBlockEnumeration_count
#print axioms BooleanAntichainsKernel.enumeratedSizedBlocks_count
