import BooleanAntichainsKernel.TopEmbeddingTransport

#print axioms BooleanAntichainsKernel.topBooleanEmbeddingCodomainEquiv
#print axioms BooleanAntichainsKernel.bottomTopBooleanEmbeddingCodomainEquiv
